{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "chartmuseum.serviceAccountName" . }}
  labels:
{{ include "chartmuseum.labels.standard" . | indent 4 }}
{{- end -}}
